server:
  port: 8000
  http:
    max-header-size: 64KB
spring:
  application:
    name: short-link-gateway
  main:
    web-application-type: reactive
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
#      discovery:
#        #自动生成路由
#        locator:
#          enabled: true
#          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: short-link-admin
          uri: lb://short-link-admin
          predicates:
            - Path=/api/short-link/admin/**
        - id: short-link-project
          uri: lb://short-link-project
          predicates:
            - Path=/api/short-link/**

knife4j:
  gateway:
    enabled: true
    strategy: discover #网关文档聚合方式：服务发现（自动聚合）
    discover:
      version: openapi3 #配置OpenAPI3规范
      enabled: true #配置开启服务发现
      excluded-services: mall-monitor #排除监控服务
    tags-sorter: order #配置tag排序规则
    operations-sorter: order #配置operation排序规则
logging:
  level:
    org.springframework.cloud.gateway: DEBUG