server:
  port: 8003
  http:
    max-header-size: 64KB

spring:
  application:
    name: short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.220.128
      port: 6379
      password: 123456
  cloud:
    nacos:
      server-addr: 192.168.220.128:8848
      discovery:
        server-addr: 192.168.220.128:8848


short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20

feign:
  inside:
    key: haole
    secret: 114514
    ips:





mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml